#!/usr/bin/env perl

use strict;

my $dwolla_account = 'Assets:Broker:Dwolla';
my $dwolla_fee_account = 'Expenses:Broker:Dwolla';

while (<>) {
    my ($type, $date, $time, $amount, $id, $original_id, $transaction_type,
        $other_entity, $other_entity_id, $comments, $address1, $address2, $city,
        $state, $zip, $email_address) = map { s/^"(.*)"$/$1/; $_ } split ',';

    next if $type eq "Type";

    my ($month, $day, $year) = $date =~ /([0-9]{2})\/([0-9]{2})\/([0-9]{4})/;
    $date = "$year/$month/$day";

    my $other_account = ($transaction_type eq 'deposit' or
                        $transaction_type eq 'withdraw') ? 'Assets' :
                        $transaction_type eq 'transfer' ?
                            ($type eq 'debit' ? 'Expenses' :
                            $type eq 'credit' ? 'Income' :
                            $dwolla_account) :
                        $type eq 'fee' ? $dwolla_fee_account :
                        $dwolla_account;

    printf "%s (#%s) %s\n", $date, $id, $other_entity;
    printf "    %s %27s\n", $dwolla_account, (sprintf "\$%.02f", -$amount);
    printf "    %s\n\n", $other_account;
}
